export default {
    "first-page": "firstPage",
    "入科": "entry",
    "床位一览": "bedBrowse",
    "质控指标": "quality",
    "公告设置": "announcement",
    "统计查询": "count",
    "医嘱属性": "advice",
    "导管维护": "pipe",
    "床位管理": "bedManage",
    "设备维护": "equipment",
    "基础字典": "dictionary",
    "监控项目维护": "monitoring",
    "评分项目维护": "grade",
    "护理措施": "nurse",
    "护理项目分组": "nurseGroup",
    "护理项目": "nurseItem",
    "统计类型维护": "countType",
    "科室维护": "department",
    "ICU床位": "icuBed",
    "角色维护": "role",
    "人员维护": "people",
    "工作站维护": "workstation"
}